name: Deploy on push to master

on:
  push:
    branches:
      - master

jobs:
  setup-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: Setup
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
      
    # Build the Docker image
    - name: Deploy
      run: |        
        bash -ex ./deploy.sh
